version: "3.8"

services:
    api_romdata:
        build:
            target: api_romdata
            args:
                MAME_GIT_TAG: ${MAME_GIT_TAG}
    api_catalog:
        build:
            target: api_catalog
        volumes:
            - ${PATH_HOST_ROMS}:/roms/:ro
            - catalog:/catalog/:rw
    worker_catalog:
        build:
            target: worker_catalog
        volumes:
            - ${PATH_HOST_ROMS}:/roms/:ro
        command: ["/roms/", "http://api_catalog:9002/next_file"]

volumes:
    catalog: