version: "3.8"

services:

    nginx:
        build:
            context: ./nginx
        depends_on:
            - romdata
            - catalog
            - verify
        ports:
            - 80:80
        volumes:
            - logs:/logs

    romdata:
        build:
            context: .
            target: romdata
            args:
                MAME_GIT_TAG: ${MAME_GIT_TAG}

    catalog:
        build:
            context: .
            target: catalog
        depends_on:
            - romdata
        volumes:
            - ${PATH_HOST_ROMS}:/roms/:ro
            - catalog:/catalog/:rw
        command: [
            "--rom_path=/roms/",
            "--catalog_data_filename=/catalog/catalog.txt",
            "--catalog_mtime_filename=/catalog/mtimes.txt",
        ]
        ports:
            - 9001:9001


    catalog_worker:
        build:
            context: .
            target: catalog_worker
        depends_on:
            - catalog
        volumes:
            - ${PATH_HOST_ROMS}:/roms/:ro
        command: [
            "--rom_path=/roms/",
            "--url_api_catalog=http://catalog:9002",
        ]
        ports:
            - 9002:9002


    verify:
        build:
            context: .
            target: verify
        depends_on:
            - romdata
            - catalog
        command: [
            "--url_api_romdata=http://romdata:9001",
            "--url_api_catalog=http://catalog:9002",
        ]
        ports:
            - 9003:9003


volumes:
    catalog:
    logs:
